version: '3.7'

services:
  api:
    build: .
    ports:
      - '3090:3000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=presupuestousr
      - MONGO_INITDB_ROOT_PASSWORD=Pr3sUpU3st0.P4ssw0rd
    volumes:
      - ./workspace:/workspace
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js  
      - type: volume
        source: mongodb_data_volume
        target: /data/db      
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: Nuevo123*
      ME_CONFIG_MONGODB_ADMINUSERNAME: presupuestousr
      ME_CONFIG_MONGODB_ADMINPASSWORD: Pr3sUpU3st0.P4ssw0rd
      ME_CONFIG_MONGODB_URL: mongodb://presupuestousr:Pr3sUpU3st0.P4ssw0rd@mongo:27017/ 
    depends_on:
      - mongo      
  
volumes:
  mongodb_data_volume: 